---

- include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- name: Ensure Jenkins is installed.
  apt:
    name: jenkins
    state: present

- name: Ensure Jenkins is started and enabled at boot.
  service:
    name: jenkins
    state: started
    enabled: yes

- include_tasks: settings.yml

- name: Flush handlers.
  meta: flush_handlers